### ISSUE TITLE
GitHub Actions Permissions

### ISSUE THREAD

**Issue by MikeGBurns** [MicroFocus/alm-octane-github-actions-integration#1]
https://github.com/MicroFocus/alm-octane-github-actions-integration/blob/7fb3c82403eb56e105bf613882884217fe315b9d/README.md?plain=1#L76

Suggested permissions...

```yml
permissions:
  contents: read
  actions: read
```
