### ISSUE TITLE
GitHub Action doesn't provide any logs

### ISSUE THREAD

**Issue by Paul-Dumrauf** [MicroFocus/alm-octane-github-actions-integration#3]
**Description:**
Using this GitHub Action has not been running as expected. The Action seems to run successfully, but there is no activity visible in ALM Octane. There are no outputs or logs available  to review and diagnose the issue.

**Expected behavior:**
The GitHub Action should execute successfully.
Logs should be generated to track progress and report any errors encountered during the Action's execution.

**Actual behavior:**
The Action is triggered and appears to be successfully, but no log output appears in the Actions tab.
It’s unclear whether the Action is starting at all or hanging at some point.
The actions runs through regardless of the connection data being correct or not.

We need assistance to correctly generate the log output so we can trace the issue.

**Our workflow YAML:**

```yaml
name: OctaneIntegration
run-name: ${{ github.actor }} connects to ALM Octane
on: [push]
env: 
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    ACTIONS_STEP_DEBUG: true
    ACTIONS_RUNNER_DEBUG: true
jobs:
  octane_integration_job:
    runs-on: ubuntu-latest
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v1.0
        id: gitHubActionsIntegration
        with:
          octaneUrl: 'octaneUrl'
          octaneSharedSpace: 'octaneSharedSpace'
          octaneWorkspace: 'octaneWorkspace'
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          serverBaseUrl: 'ourRepo'
          unitTestResultsGlobPattern: "**/*.xml"
```

Thank you in advance for your support!
